name: Grade

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  grade:
    uses: WaffleStudio24-5/spring-seminar-judge/.github/workflows/grade.yml@main
    with:
      assignment: main
